# WiFi
wifi_ssid: "TU_SSID"
wifi_password: "TU_PASSWORD"

# Gateway encryption key (genera con: openssl rand -base64 32)
gateway_api_encryption_key: "cambiar_por_clave_base64_de_32_bytes"

# OTA password
gateway_ota_password: "cambiar_por_password_ota"
